# Generated by Django 3.1.3 on 2020-11-28 14:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateTimeField(blank=True, null=True)),
                ('website', models.TextField(blank=True)),
                ('degree', models.TextField(blank=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('freelance', models.BooleanField(default=False)),
                ('heading', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('profile_captions_csv', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('webtitle', models.TextField(blank=True)),
            ],
        ),
    ]
